services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@db:5432/yapyap
      NEO4J_URL: neo4j+ssc://hackatum-one.graphdatabase.ninja:443
      NEO4J_USER: attendee12
      NEO4J_PASSWORD: EXPL$76699
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yapyap
    ports:
      - "5432:5432"
    volumes:
      - ./example/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data: