services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yapyap
    ports:
      - "5432:5432"
    volumes:
      - ./example/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data: